### PR TITLE
inverse angstrom unit

### PR DESCRIPTION
**Pull request by OwenArnold**
Small but useful addition for working in reciprocal space

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
Out of interest, what is this for?

**Comment by OwenArnold** [comment]
@SimonHeybrock for working in reciprocal space. For example a 3D HKL data representation, or output of SofQW etc.

**Comment by SimonHeybrock** [comment]
@OwenArnold Shouldn't that have a momentum unit? See, e.g., `meV /c`, which is already supported.

**Comment by OwenArnold** [comment]
@SimonHeybrock reciprocal space units are 1/A, though for QLab, QSample do measure momentum transfer.

**Comment by OwenArnold** [comment]
As discussed. No UB matrix in dataset and will not be needed at present in the rollout plan, so converting to reciprocal lattice vectors would not be possible at present.

Demonstrating that one can provide the correct units for imported data of limited use for now.

**Pull request closed without merging**
